import type { SsgParams } from "./ssg-params";
export default SSG;

declare namespace SSG {
  const cfg: SsgParams;
  function addClasses(): void;
  function beforeRun(): void;
  function run(event: any): boolean;
  function setVariables(): void;
  function findImage(imgArray: any, searchedImg: any, order: any): number | undefined;
  function getHash(justResult: any): number | null;
  function FSmode(event: any): void;
  function createGallery(event: any): void;
  function initGallery(event: any): void;
  function onOrientationChanged(): void;
  function forceLandscapeMode(event: any, throwAlert: any): void;
  function iphoneShit(event: any): void;
  function iphoneScrollBlock(): void;
  function slideBrowse(event: any): void;
  function slideScroll(): void;
  function slideEnd(event: any): void;
  function slideStart(event: any): void;
  function setNotchRight(): void;
  function hasClass(classList: any, classToFind: any): boolean;
  function keyFunction(event: any): void;
  function touchScroll(event: any): void;
  function getAlt(el: any): any;
  function getImgList(event: any): void;
  function onFS(): void;
  function refreshPos(): void;
  function countResize(): void;
  function scrollToActualImg(): void;
  function refreshFormat(): void;
  function onResize(): void;
  function displayFormat(e: any): void;
  function onImageLoad(event: any): Promise<void>;
  function getExif(exif: any, captionInfo: any): string;
  function onLoadError(event: any): void;
  function escapeHtml(string: any): string;
  function shareMenu(newOne: any, caption: any): string;
  function addImage(): void;
  function beyondGallery(): void;
  function getName(url: any): any;
  function setHashGA(index: any): void;
  function metronome(): void;
  function ScrollTo(posY: any, direction: any): void;
  function jumpScroll(): void;
  function countImageIndent(index: any): number;
  function seizeScrolling(e: any): void;
  function openFullscreen(): void;
  function closeFullscreen(): void;
  function createDataObject(imgIndex: any): {
    imgCount: any;
    GalleryId: any;
    imgGalleryId: any;
    imgPageId: any;
    imgPath: any;
    imgName: any;
    imageCaption: any;
  };
  function onHashExit(): void;
  function preventExit(): void;
  function restart(config: any): void;
  function destroyGallery(mode: any): void;
  function showFsTip(content: any): void;
}
