export default SSG;
declare namespace SSG {
    namespace cfg {
        const scrollDuration: number;
        const alwaysFullscreen: boolean;
        const neverFullscreen: boolean;
        const mobilePortraitFS: boolean;
        const theme: string;
        const crossCursor: boolean;
        const fileToLoad: any;
        const socialShare: boolean;
        const hideImgCaptions: boolean;
        const enlargeImg: boolean;
        const captionExif: string;
        const logIntoGA: boolean;
        const rightClickProtection: boolean;
        const preferedCaptionLocation: number;
        const sideCaptionforSmallerLandscapeImg: boolean;
        const globalAuthorCaption: string;
        const showFirst3ImgsTogether: boolean;
        const scaleLock1: boolean;
        const observeDOM: boolean;
        const imgBorderWidthX: number;
        const imgBorderWidthY: number;
        const imgBorderColor: string;
        const imgOutlineColor: string;
        const imgBorderLightFx: boolean;
        const imgBorderRadius: number;
        const imgBorderShadow: boolean;
        const watermarkWidth: number;
        const watermarkImage: string;
        const watermarkText: string;
        const watermarkFontColor: string;
        const watermarkFontSize: number;
        const watermarkOffsetX: number;
        const watermarkOffsetY: number;
        const watermarkOpacity: number;
        const hint1: string;
        const hint2: string;
        const hint3: string;
        const hintTouch: string;
        const hintFS: string;
        const toTheTop: string;
        const exitLink: string;
        const imageLink: string;
        const copyButton: string;
        const linkPaste: string;
        const showLandscapeHint: boolean;
        const landscapeHint: string;
        const onGalleryStart: any;
        const onImgScrollsIn: any;
        const onImgView: any;
        const onImgLoad: any;
        const onOrientationChange: any;
        const onBeyondGallery: any;
        const onGalleryExit: any;
    }
    function addClasses(): void;
    function beforeRun(): void;
    function run(event: any): boolean;
    function setVariables(): void;
    function getHash(justResult: any): number | null;
    function FSmode(event: any): void;
    function createGallery(event: any): void;
    function initGallery(event: any): void;
    function orientationChanged(): void;
    function iphoneShit(event: any): void;
    function iphoneScrollBlock(): void;
    function slideBrowse(event: any): void;
    function slideStart(event: any): void;
    function setNotchRight(): void;
    function hasClass(classList: any, classToFind: any): boolean;
    function keyFunction(event: any): void;
    function touchScroll(event: any): void;
    function getAlt(el: any): any;
    function getImgList(event: any): void;
    function onFS(): void;
    function refreshPos(): void;
    function countResize(): void;
    function scrollToActualImg(): void;
    function refreshFormat(): void;
    function onResize(): void;
    function displayFormat(e: any): void;
    function onImageLoad(event: any): Promise<void>;
    function getExif(exif: any, captionInfo: any): string;
    function onLoadError(event: any): void;
    function escapeHtml(string: any): string;
    function shareMenu(newOne: any, caption: any): string;
    function addImage(): void;
    function beyondGallery(): void;
    function getName(url: any): any;
    function setHashGA(index: any): void;
    function metronome(): void;
    function ScrollTo(posY: any, direction: any): void;
    function jumpScroll(): void;
    function countImageIndent(index: any): number;
    function seizeScrolling(e: any): void;
    function openFullscreen(): void;
    function closeFullscreen(): void;
    function createDataObject(imgIndex: any): {
        imgCount: any;
        GalleryId: any;
        imgGalleryId: any;
        imgPageId: any;
        imgPath: any;
        imgName: any;
        imageCaption: any;
    };
    function onHashExit(): void;
    function preventExit(): void;
    function restart(config: any): void;
    function destroyGallery(mode: any): void;
    function showFsTip(content: any): void;
}
